### ISSUE TITLE
Some help about your CurveInterpolator2D

### ISSUE THREAD

**Issue by pedefe** [kjerandp/curve-interpolator#12]
Hello,
- In order to drive a vehicle following such a line, I need to know the "projection" of the current position of vehicle on the curve (the point where the 'normal' vector on curve intersects the current position of vehicle. How can I compute this projection ?
- How can I draw the curve on a canvas in js ?
Best regards.

**Comment by kjerandp** [comment]
Hi.

I've made an example for you to look at here: https://observablehq.com/@kjerandp/curve-interpolator-issue-12

Note that the CureveInterpolator2D class was included for legacy reasons, and you should consider using the standard CurveInterpolator class instead (as used in example above).

I hope this answer your question. If not, let me know, otherwise please close this issue :-)

**Comment by pedefe** [comment]
Very clear and detailled answer.
Thank you very much for this job.
Best regards.
